#!/usr/bin/env python

import sys

import plover.gui.main
import plover.oslayer.processlock

try:
    # Ensure only one instance of Plover is running at a time.
    with plover.oslayer.processlock.PloverLock():
        gui = plover.gui.main.PloverGUI()
        gui.MainLoop()
except plover.oslayer.processlock.LockNotAcquiredException:
    print 'Another instance of Plover is already running.'
except:
    print "Unexpected error:", sys.exc_info()[0]
    raise
