# .readthedocs.yml
# Read the Docs configuration file

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/conf.py
